name: "Test and lint"

on:
  push:
  pull_request:
    branches:
      - "main"

permissions:
  contents: "read"

jobs:
  test_and_lint:

    runs-on: "ubuntu-latest"

    steps:
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install libgirepository1.0-dev libcairo-dev libglib2.0-dev libdbus-1-dev
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"
          cache: "pip"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -c requirements.txt -e ".[test]"
      - name: "Lint with flake8"
        run: "flake8" 
      - name: "Check types with mypy"
        run: "mypy --strict src"
      - name: "Test with pytest"
        run: "pytest"
